import { 
  Home, 
  Info, 
  Car, 
  Trophy, 
  Award, 
  Users, 
  HandCoins, 
  Mail, 
  Calendar,
  ChevronRight,
  ArrowRight,
  Clock,
  MapPin,
  Zap,
  Leaf,
  Battery,
  Gauge,
  Sparkles,
  Target,
  Rocket,
  CheckCircle2,
  ChevronDown,
  ChevronUp,
  ExternalLink,
  Github,
  Twitter,
  Instagram,
  Linkedin,
  Facebook,
  Youtube,
  Menu,
  X,
  type LucideIcon
} from "lucide-react";

export const Icons = {
  home: Home,
  info: Info,
  car: Car,
  trophy: Trophy,
  award: Award,
  users: Users,
  handCoins: HandCoins,
  mail: Mail,
  calendar: Calendar,
  chevronRight: ChevronRight,
  arrowRight: ArrowRight,
  clock: Clock,
  mapPin: MapPin,
  zap: Zap,
  leaf: Leaf,
  battery: Battery,
  gauge: Gauge,
  sparkles: Sparkles,
  target: Target,
  rocket: Rocket,
  check: CheckCircle2,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  external: ExternalLink,
  github: Github,
  twitter: Twitter,
  instagram: Instagram,
  linkedin: Linkedin,
  facebook: Facebook,
  youtube: Youtube,
  menu: Menu,
  close: X,
} as const;

export type IconName = keyof typeof Icons;

export const getIcon = (name: IconName): LucideIcon => {
  return Icons[name] || Icons.info; // Default to info icon if not found
};

export const iconVariants = {
  size: {
    xs: 'h-3 w-3',
    sm: 'h-4 w-4',
    md: 'h-5 w-5',
    lg: 'h-6 w-6',
    xl: 'h-8 w-8',
  },
  color: {
    default: 'text-foreground',
    primary: 'text-primary',
    secondary: 'text-secondary-foreground',
    success: 'text-green-500 dark:text-green-400',
    warning: 'text-amber-500 dark:text-amber-400',
    danger: 'text-red-500 dark:text-red-400',
    muted: 'text-muted-foreground',
  },
  bg: {
    default: 'bg-muted',
    primary: 'bg-primary/10',
    success: 'bg-green-100 dark:bg-green-900/30',
    warning: 'bg-amber-100 dark:bg-amber-900/30',
    danger: 'bg-red-100 dark:bg-red-900/30',
    muted: 'bg-muted',
  },
} as const;
